### ISSUE TITLE
Trained Model Request

### ISSUE THREAD

**Issue by AndresJGComfa** [hanyin88/DRG-LLaMA#1]
Hello, I have been reviewing your work and I can run the codes and train the models. But, it requires so much time. Can you share the trained models or the model snapshots? Thank you

**Comment by hanyin88** [comment]
Hello there and sorry for seeing this late!! I also apologize that based on the user agreement of MIMIC, I think we are not suppose to share trained model weights... Apologize for the inconvenience, and yes, it's quite slow to train...
