### ISSUE TITLE
Cannot find discharge.csv in mimic iv dataset

### ISSUE THREAD

**Issue by annihi1ation** [hanyin88/DRG-LLaMA#2]
Dear Dr. Hanyin,

I am trying to retrain your model. However, I can't find the discharge.csv in the mimic iv website even though I have access. Could you please help me to find the dataset?

Thanks

**Comment by hanyin88** [comment]
Thanks for the interest in our work! Here you go and it's in a different dataset: https://physionet.org/content/mimic-iv-note/2.2/

**Comment by hanyin88** [comment]
Fixed

**Comment by annihi1ation** [comment]
Thanks a lot, Dr. Hanyin! You really helped me a lot 😃

Hanyin Wang ***@***.***> 于2024年1月25日周四 18:14写道：
